// ========== CONFIGURATION ==========
const DB_URL = 'https://kutmygkodxtfbtdtwqef.supabase.co';
const DB_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1dG15Z2tvZHh0ZmJ0ZHR3cWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyOTY4MzQsImV4cCI6MjA4Njg3MjgzNH0.LDd6RFbjSjF6QYqi__f7zK1oI8Ze7sa1Vv-1t2TLtkE';
const HF_TOKEN = "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"; 

const client = window.supabase.createClient(DB_URL, DB_KEY);
let user = null;
let selectedFile = null;

// ========== BEAUTIFUL MARKDOWN RENDERER ==========
function formatMarkdown(text) {
    if (!text) return "";
    return text
        .replace(/^# (.*$)/gm, '<h1 class="text-3xl font-black text-blue-400 my-6 tracking-tight">$1</h1>')
        .replace(/^## (.*$)/gm, '<h2 class="text-xl font-bold text-blue-300 mt-8 mb-4 border-b border-white/10 pb-2">$1</h2>')
        .replace(/^### (.*$)/gm, '<h3 class="text-lg font-bold text-blue-200 mt-6 mb-2">$1</h3>')
        .replace(/\*\*(.*?)\*\*/g, '<strong class="text-white font-bold">$1</strong>')
        .replace(/`([^`]+)`/g, '<code class="bg-slate-700/50 text-pink-400 px-1.5 py-0.5 rounded font-mono text-xs">$1</code>')
        .replace(/```([\s\S]*?)```/g, '<pre class="bg-black/60 p-5 rounded-2xl my-6 border border-white/5 overflow-x-auto font-mono text-green-400 text-xs leading-relaxed">$1</pre>')
        .replace(/\n/g, '<br>');
}

// ========== CORE ENGINE (SURVIVAL MODE) ==========
async function generateReadme() {
    const input = document.getElementById('message-input');
    const loading = document.getElementById('loading-indicator');
    const chatDisplay = document.getElementById('chat-messages');
    
    if (!selectedFile) return alert("Please upload your code first!");

    // 1. Check Balance BEFORE everything
    const { data: profile, error: pErr } = await client.from('profiles').select('credits').eq('id', user.id).single();
    if (pErr || profile.credits < 0.50) return alert("Insufficient Balance ($0.50 required)");

    loading.classList.remove('hidden');
    chatDisplay.innerHTML = `<div class="text-center py-20 animate-pulse font-mono text-blue-400">SELECTING BEST ENGINE...</div>`;

    const modelStack = [
        "deepseek-ai/DeepSeek-V3", 
        "Qwen/Qwen2.5-Coder-32B-Instruct",
        "Qwen/Qwen2.5-Coder-7B-Instruct"
    ];

    let fileContent = await selectedFile.text();
    let finalReadme = null;
    let usedModel = "";

    // 2. Fallback Logic: Try models until one works
    for (let modelName of modelStack) {
        if (finalReadme) break;
        try {
            const response = await fetch("https://router.huggingface.co/v1/chat/completions", {
                method: "POST",
                headers: { "Authorization": `Bearer ${HF_TOKEN}`, "Content-Type": "application/json" },
                body: JSON.stringify({
                    "model": modelName,
                    "messages": [
                        { "role": "system", "content": "Output ONLY raw markdown README. No intro text, no conversational filler." },
                        { "role": "user", "content": `User Instructions: ${input.value}\n\nCode:\n${fileContent}` }
                    ],
                    "max_tokens": 2000
                })
            });

            if (response.ok) {
                const result = await response.json();
                finalReadme = result.choices[0].message.content;
                usedModel = modelName;
            } else {
                console.warn(`Model ${modelName} failed with status ${response.status}`);
            }
        } catch (e) { console.error(`Failed on ${modelName}`); }
    }

    // 3. Deduction & UI Rendering
    if (finalReadme) {
        // DEDUCT ONLY ON SUCCESS
        const newCredits = profile.credits - 0.50;
        await client.from('profiles').update({ credits: newCredits }).eq('id', user.id);
        document.getElementById('balance').innerText = newCredits.toFixed(2);

        loading.classList.add('hidden');
        chatDisplay.innerHTML = `
            <div class="bg-slate-800/40 p-8 rounded-3xl border border-white/10 shadow-2xl relative group">
                <div class="absolute -top-3 left-6 bg-blue-600 text-[9px] px-2 py-0.5 rounded-full font-mono uppercase tracking-widest">Generated by ${usedModel.split('/')[1]}</div>
                <button onclick="navigator.clipboard.writeText(\`${finalReadme.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`)" 
                        class="absolute top-6 right-6 bg-white/5 hover:bg-blue-600 text-white text-[10px] uppercase font-bold px-4 py-2 rounded-lg transition-all">
                    Copy
                </button>
                <div class="markdown-body">${formatMarkdown(finalReadme)}</div>
                <button id="dl-final" class="mt-8 w-full bg-blue-600 hover:bg-blue-500 p-4 rounded-2xl font-black uppercase tracking-widest transition-all">
                    Download README.md
                </button>
            </div>`;

        document.getElementById('dl-final').onclick = () => {
            const blob = new Blob([finalReadme], { type: 'text/markdown' });
            const a = document.createElement('a');
            a.href = URL.createObjectURL(blob); a.download = "README.md"; a.click();
        };
    } else {
        loading.classList.add('hidden');
        chatDisplay.innerHTML = `<p class="text-red-400 text-center font-mono py-10">ERROR: All models reached free limits. Try again later. No credits deducted.</p>`;
    }
}

// ========== AUTH & UI HELPERS ==========
document.addEventListener('DOMContentLoaded', () => {
    const fileInput = document.getElementById('file-input');
    document.getElementById('file-upload-btn').onclick = () => fileInput.click();
    document.getElementById('send-message-btn').onclick = generateReadme;
    
    fileInput.onchange = (e) => {
        if (e.target.files[0]) {
            selectedFile = e.target.files[0];
            document.getElementById('file-name').innerText = selectedFile.name;
            document.getElementById('file-preview').classList.remove('hidden');
        }
    };
});

// Auth Persistence
client.auth.getSession().then(({ data: { session } }) => { 
    if (session) { user = session.user; showDashboard(); } 
});

function showDashboard() {
    document.getElementById('auth-screen').classList.add('hidden');
    document.getElementById('dashboard-screen').classList.remove('hidden');
    client.from('profiles').select('credits').eq('id', user.id).single().then(({data}) => {
        if(data) document.getElementById('balance').innerText = data.credits.toFixed(2);
    });
}

window.handleSignOut = async () => { await client.auth.signOut(); location.reload(); };
